# Generated by Django 3.2.17 on 2023-03-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amalkardmeghdarititle',
            fields=[
                ('code', models.IntegerField(db_column='Code', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Title', max_length=150, null=True)),
            ],
            options={
                'db_table': 'AmalkardMeghdariTitle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Amalkardmeghdarivalue',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tid', models.IntegerField(blank=True, db_column='TID', null=True)),
                ('date', models.DecimalField(blank=True, db_column='Date', decimal_places=0, max_digits=18, null=True)),
                ('price', models.DecimalField(blank=True, db_column='Price', decimal_places=0, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'AmalkardMeghdariValue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Amalkardton',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tid', models.IntegerField(blank=True, db_column='TID', null=True)),
                ('date', models.DecimalField(blank=True, db_column='Date', decimal_places=0, max_digits=18, null=True)),
                ('ton', models.DecimalField(blank=True, db_column='Ton', decimal_places=0, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'AmalkardTon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Amountspec',
            fields=[
                ('calcid', models.AutoField(db_column='CalcID', primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Date', max_length=10, null=True)),
                ('prodid', models.IntegerField(blank=True, db_column='ProdID', null=True)),
                ('sarak', models.DecimalField(blank=True, db_column='Sarak', decimal_places=0, max_digits=18, null=True)),
                ('transfrom', models.DecimalField(blank=True, db_column='TransFrom', decimal_places=0, max_digits=18, null=True)),
                ('transto', models.DecimalField(blank=True, db_column='TransTo', decimal_places=0, max_digits=18, null=True)),
                ('consumed', models.DecimalField(blank=True, db_column='Consumed', decimal_places=0, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'AmountSpec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str1', models.CharField(blank=True, db_collation='Arabic_BIN', max_length=50, null=True)),
                ('str2', models.CharField(blank=True, db_collation='Arabic_BIN', max_length=50, null=True)),
            ],
            options={
                'db_table': 'asd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Arabic_BIN', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Arabic_BIN', max_length=255)),
                ('codename', models.CharField(db_collation='Arabic_BIN', max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_collation='Arabic_BIN', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(db_collation='Arabic_BIN', max_length=150, unique=True)),
                ('first_name', models.CharField(db_collation='Arabic_BIN', max_length=150)),
                ('last_name', models.CharField(db_collation='Arabic_BIN', max_length=150)),
                ('email', models.CharField(db_collation='Arabic_BIN', max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Balancetitles',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Title', max_length=150, null=True)),
                ('isdaryafti', models.BooleanField(blank=True, db_column='ISDaryafti', null=True)),
                ('calculationmode', models.BooleanField(blank=True, db_column='CalculationMode', null=True)),
                ('stationid', models.IntegerField(blank=True, db_column='StationID', null=True)),
                ('tanktype', models.SmallIntegerField(blank=True, db_column='TankType', null=True)),
                ('priority', models.IntegerField(blank=True, db_column='Priority', null=True)),
            ],
            options={
                'db_table': 'BalanceTitles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Billedition',
            fields=[
                ('yrid', models.AutoField(db_column='YRID', primary_key=True, serialize=False)),
                ('stationid', models.IntegerField(blank=True, db_column='StationID', null=True)),
                ('prodid', models.IntegerField(blank=True, db_column='ProdID', null=True)),
                ('date', models.DecimalField(blank=True, db_column='Date', decimal_places=0, max_digits=18, null=True)),
                ('litr60', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Litr60', max_length=20, null=True)),
                ('type', models.SmallIntegerField(blank=True, db_column='Type', null=True)),
            ],
            options={
                'db_table': 'BillEdition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Billedition2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yrid', models.IntegerField(db_column='YRID')),
                ('stationid', models.IntegerField(blank=True, db_column='StationID', null=True)),
                ('prodid', models.IntegerField(blank=True, db_column='ProdID', null=True)),
                ('date', models.DecimalField(blank=True, db_column='Date', decimal_places=0, max_digits=18, null=True)),
                ('litr60', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Litr60', max_length=20, null=True)),
                ('type', models.SmallIntegerField(blank=True, db_column='Type', null=True)),
            ],
            options={
                'db_table': 'BillEdition2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calibrationpi',
            fields=[
                ('calibrid', models.BigAutoField(db_column='CalibrID', primary_key=True, serialize=False)),
                ('tankid', models.IntegerField(blank=True, db_column='TankID', null=True)),
                ('liters', models.DecimalField(blank=True, db_column='Liters', decimal_places=0, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'CalibrationPI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Constmounth',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('stationid', models.IntegerField(blank=True, db_column='StationID', null=True)),
                ('date', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Date', max_length=10, null=True)),
                ('prid', models.IntegerField(blank=True, db_column='PrId', null=True)),
                ('tot', models.DecimalField(blank=True, db_column='Tot', decimal_places=0, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'ConstMounth',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consumptionmarakez',
            fields=[
                ('stationid', models.IntegerField(db_column='StationID', primary_key=True, serialize=False)),
                ('rdate', models.CharField(db_collation='Arabic_BIN', db_column='RDate', max_length=10)),
                ('productid', models.IntegerField(db_column='ProductId')),
                ('litr60', models.BigIntegerField(blank=True, db_column='Litr60', null=True)),
            ],
            options={
                'db_table': 'ConsumptionMarakez',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dailyreplinestations',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('linecode', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='LineCode', max_length=20, null=True)),
                ('stationid', models.IntegerField(blank=True, db_column='StationID', null=True)),
            ],
            options={
                'db_table': 'DailyRepLineStations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dailyreplineval',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('linecode', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='LineCode', max_length=20, null=True)),
                ('rdate', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='RDate', max_length=10, null=True)),
                ('prodid', models.IntegerField(blank=True, db_column='ProdId', null=True)),
                ('value', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Value', max_length=50, null=True)),
            ],
            options={
                'db_table': 'DailyRepLineVal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dailyrepmanual',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('rdate', models.DecimalField(blank=True, db_column='RDate', decimal_places=0, max_digits=18, null=True)),
                ('lid', models.IntegerField(blank=True, db_column='LID', null=True)),
                ('stationid', models.IntegerField(blank=True, db_column='StationID', null=True)),
                ('prodid', models.IntegerField(blank=True, db_column='ProdID', null=True)),
                ('amount', models.DecimalField(blank=True, db_column='Amount', decimal_places=0, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'DailyRepManual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dailyreportset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationid', models.IntegerField(blank=True, db_column='StationID', null=True)),
                ('reyentered', models.BooleanField(blank=True, db_column='ReyEntered', null=True)),
            ],
            options={
                'db_table': 'DailyReportSet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dailyrepstation',
            fields=[
                ('did', models.AutoField(db_column='DID', primary_key=True, serialize=False)),
                ('lid', models.IntegerField(blank=True, db_column='LID', null=True)),
                ('stationid', models.IntegerField(blank=True, db_column='StationID', null=True)),
                ('priority', models.IntegerField(blank=True, db_column='Priority', null=True)),
                ('type', models.SmallIntegerField(blank=True, db_column='Type', null=True)),
            ],
            options={
                'db_table': 'DailyRepStation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Daliyrepline',
            fields=[
                ('lid', models.AutoField(db_column='LID', primary_key=True, serialize=False)),
                ('linename', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='LineName', max_length=150, null=True)),
            ],
            options={
                'db_table': 'DaliyRepLine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Daycalc',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('makhzanname', models.TextField(blank=True, db_collation='Arabic_BIN', db_column='MakhzanName', null=True)),
                ('istgahname', models.TextField(blank=True, db_collation='Arabic_BIN', db_column='Istgahname', null=True)),
                ('productname', models.TextField(blank=True, db_collation='Arabic_BIN', db_column='ProductName', null=True)),
                ('ghabz', models.TextField(blank=True, db_collation='Arabic_BIN', db_column='Ghabz', null=True)),
                ('ekhtelaf', models.BigIntegerField(blank=True, db_column='Ekhtelaf', null=True)),
                ('datenow', models.TextField(blank=True, db_collation='Arabic_BIN', db_column='DateNow', null=True)),
                ('datereport', models.TextField(blank=True, db_collation='Arabic_BIN', db_column='DateReport', null=True)),
                ('tankid', models.TextField(blank=True, db_collation='Arabic_BIN', db_column='TankId', null=True)),
                ('stationid', models.TextField(blank=True, db_collation='Arabic_BIN', db_column='StationId', null=True)),
                ('productid', models.TextField(blank=True, db_collation='Arabic_BIN', db_column='Productid', null=True)),
                ('sid', models.IntegerField(blank=True, db_column='Sid', null=True)),
                ('year', models.TextField(blank=True, db_collation='Arabic_BIN', db_column='Year', null=True)),
                ('mount', models.TextField(blank=True, db_collation='Arabic_BIN', db_column='Mount', null=True)),
                ('sumdgree', models.TextField(blank=True, db_collation='Arabic_BIN', db_column='Sumdgree', null=True)),
                ('sumkarkard', models.TextField(blank=True, db_collation='Arabic_BIN', db_column='Sumkarkard', null=True)),
            ],
            options={
                'db_table': 'DayCalc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detailtank',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('thankid', models.IntegerField(blank=True, db_column='ThankId', null=True)),
                ('start', models.DecimalField(blank=True, db_column='Start', decimal_places=0, max_digits=18, null=True)),
                ('inc', models.DecimalField(blank=True, db_column='Inc', decimal_places=0, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'DetailTank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detailtaraz',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('btid', models.IntegerField(blank=True, db_column='BTID', null=True)),
                ('date', models.DecimalField(blank=True, db_column='Date', decimal_places=0, max_digits=18, null=True)),
                ('pid', models.IntegerField(blank=True, db_column='PId', null=True)),
                ('price', models.DecimalField(blank=True, db_column='Price', decimal_places=0, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'DetailTaraz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, db_collation='Arabic_BIN', null=True)),
                ('object_repr', models.CharField(db_collation='Arabic_BIN', max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField(db_collation='Arabic_BIN')),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_collation='Arabic_BIN', max_length=100)),
                ('model', models.CharField(db_collation='Arabic_BIN', max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(db_collation='Arabic_BIN', max_length=255)),
                ('name', models.CharField(db_collation='Arabic_BIN', max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(db_collation='Arabic_BIN', max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(db_collation='Arabic_BIN')),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Editionratio',
            fields=[
                ('rid', models.AutoField(db_column='RID', primary_key=True, serialize=False)),
                ('prodid', models.IntegerField(blank=True, db_column='ProdID', null=True)),
                ('temprature', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Temprature', max_length=20, null=True)),
                ('api', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='API', max_length=10, null=True)),
                ('ratio', models.DecimalField(blank=True, db_column='Ratio', decimal_places=4, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'EditionRatio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exceldbcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excelcode', models.IntegerField(blank=True, db_column='ExcelCode', null=True)),
                ('dbcode', models.IntegerField(blank=True, db_column='DBCode', null=True)),
            ],
            options={
                'db_table': 'EXCELDBCode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fraction',
            fields=[
                ('fractionid', models.AutoField(db_column='FractionID', primary_key=True, serialize=False)),
                ('tankid', models.IntegerField(blank=True, db_column='TankID', null=True)),
                ('milno', models.DecimalField(blank=True, db_column='MilNo', decimal_places=0, max_digits=18, null=True)),
                ('litr', models.DecimalField(blank=True, db_column='Litr', decimal_places=0, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'Fraction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fractionlitr',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('tankid', models.IntegerField(blank=True, db_column='TankID', null=True)),
                ('litr', models.IntegerField(blank=True, db_column='Litr', null=True)),
                ('ll', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'FractionLitr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Linecapacity1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linecode', models.CharField(blank=True, db_collation='Arabic_BIN', max_length=10, null=True)),
                ('capacity', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'linecapacity1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Linedetails',
            fields=[
                ('linedetid', models.AutoField(db_column='LineDetID', primary_key=True, serialize=False)),
                ('linecode', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='LineCode', max_length=20, null=True)),
                ('stationid', models.IntegerField(blank=True, db_column='StationID', null=True)),
                ('prodid', models.IntegerField(blank=True, db_column='ProdID', null=True)),
                ('gravity', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Gravity', max_length=20, null=True)),
                ('length', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Length', max_length=20, null=True)),
            ],
            options={
                'db_table': 'LineDetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Linepriority',
            fields=[
                ('spid', models.AutoField(db_column='SPID', primary_key=True, serialize=False)),
                ('linecode', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='LineCode', max_length=20, null=True)),
                ('priority', models.IntegerField(blank=True, db_column='Priority', null=True)),
            ],
            options={
                'db_table': 'LinePriority',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lines',
            fields=[
                ('lineid', models.AutoField(db_column='LineID', primary_key=True, serialize=False)),
                ('linecode', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='LineCode', max_length=20, null=True)),
                ('linename', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='LineName', max_length=100, null=True)),
                ('diameter', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Diameter', max_length=10, null=True)),
                ('linekm', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='LineKm', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Lines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainappTankcalcmetric',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tankid', models.IntegerField(db_column='TankID')),
                ('rdate', models.CharField(db_collation='Arabic_BIN', db_column='RDate', max_length=10)),
                ('billid', models.CharField(db_collation='Arabic_BIN', db_column='BillID', max_length=10)),
                ('size', models.CharField(db_collation='Arabic_BIN', db_column='Size', max_length=20)),
                ('temprature', models.CharField(db_collation='Arabic_BIN', db_column='Temprature', max_length=20)),
                ('water', models.CharField(db_collation='Arabic_BIN', db_column='Water', max_length=20)),
                ('status', models.IntegerField(db_column='Status')),
                ('specweight', models.CharField(db_collation='Arabic_BIN', db_column='SpecWeight', max_length=20)),
                ('refinery', models.CharField(db_collation='Arabic_BIN', db_column='Refinery', max_length=50)),
                ('naturallitr', models.CharField(db_collation='Arabic_BIN', db_column='NaturalLitr', max_length=50)),
                ('litr60', models.CharField(db_collation='Arabic_BIN', db_column='Litr60', max_length=20)),
                ('hour', models.CharField(db_collation='Arabic_BIN', db_column='Hour', max_length=20)),
                ('cyear', models.IntegerField(db_column='CYear')),
                ('envtemp', models.CharField(db_collation='Arabic_BIN', db_column='EnvTemp', max_length=20)),
            ],
            options={
                'db_table': 'mainapp_tankcalcmetric',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Monthlyrepdate',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('expdate', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='EXPdate', max_length=10, null=True)),
            ],
            options={
                'db_table': 'MonthlyRepDate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mountprint',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('istgahname', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='IstgahName', max_length=250, null=True)),
                ('makhzancode', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='MakhzanCode', max_length=250, null=True)),
                ('productname', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='ProductName', max_length=250, null=True)),
                ('ticket', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Ticket', max_length=250, null=True)),
                ('statee', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Statee', max_length=250, null=True)),
                ('day', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Day', max_length=250, null=True)),
                ('time', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Time', max_length=250, null=True)),
                ('size', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Size', max_length=250, null=True)),
                ('dgree', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Dgree', max_length=250, null=True)),
                ('water', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Water', max_length=250, null=True)),
                ('nlitre', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='NLitre', max_length=250, null=True)),
                ('litertahvili', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='LiterTahvili', max_length=250, null=True)),
                ('tafavoottabiiei', models.DecimalField(blank=True, db_column='TafavootTabiiei', decimal_places=0, max_digits=18, null=True)),
                ('tafavoot60', models.DecimalField(blank=True, db_column='Tafavoot60', decimal_places=0, max_digits=18, null=True)),
                ('dateaz', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='DateAz', max_length=250, null=True)),
                ('dateta', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='DateTa', max_length=250, null=True)),
                ('sid', models.IntegerField(blank=True, db_column='Sid', null=True)),
            ],
            options={
                'db_table': 'MountPrint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nirogahvalues',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('rdate', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='RDate', max_length=10, null=True)),
                ('stationid', models.IntegerField(blank=True, db_column='StationID', null=True)),
                ('value', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Value', max_length=50, null=True)),
                ('prodid', models.IntegerField(blank=True, db_column='ProdID', null=True)),
            ],
            options={
                'db_table': 'NirogahValues',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oilnew',
            fields=[
                ('a1', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='A1', max_length=50, null=True)),
                ('a2', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='A2', max_length=50, null=True)),
                ('a3', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='A3', max_length=50, null=True)),
                ('id', models.IntegerField(blank=True, db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'oilnew',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oilproducts',
            fields=[
                ('prodid', models.AutoField(db_column='ProdID', primary_key=True, serialize=False)),
                ('prodname', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='ProdName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'OilProducts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oiltazrigh',
            fields=[
                ('tid', models.AutoField(db_column='TID', primary_key=True, serialize=False)),
                ('prodid', models.IntegerField(blank=True, db_column='ProdID', null=True)),
                ('amount', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Amount', max_length=50, null=True)),
                ('date', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Date', max_length=10, null=True)),
                ('stationid', models.IntegerField(blank=True, db_column='StationID', null=True)),
            ],
            options={
                'db_table': 'OilTazrigh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Palayeshgahvalues',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('rdate', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='RDate', max_length=10, null=True)),
                ('stationid', models.IntegerField(blank=True, db_column='StationID', null=True)),
                ('value', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Value', max_length=50, null=True)),
                ('prodid', models.IntegerField(blank=True, db_column='ProdID', null=True)),
            ],
            options={
                'db_table': 'PalayeshgahValues',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productpriority',
            fields=[
                ('ppid', models.AutoField(db_column='PPID', primary_key=True, serialize=False)),
                ('prodid', models.IntegerField(blank=True, db_column='ProdID', null=True)),
                ('priority', models.IntegerField(blank=True, db_column='Priority', null=True)),
            ],
            options={
                'db_table': 'ProductPriority',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rawoildetailkarkard',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('kid', models.IntegerField(blank=True, db_column='KID', null=True)),
                ('date', models.DecimalField(blank=True, db_column='Date', decimal_places=0, max_digits=18, null=True)),
                ('price', models.DecimalField(blank=True, db_column='Price', decimal_places=0, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'RawOilDetailKarkard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rawoildetailtaraz',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('btid', models.IntegerField(blank=True, db_column='BTID', null=True)),
                ('date', models.DecimalField(blank=True, db_column='Date', decimal_places=0, max_digits=18, null=True)),
                ('lineid', models.IntegerField(blank=True, db_column='LineID', null=True)),
                ('price', models.DecimalField(blank=True, db_column='Price', decimal_places=0, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'RawOilDetailTaraz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rawoilkarkard',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('linecode', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='LineCode', max_length=20, null=True)),
                ('tid', models.IntegerField(blank=True, db_column='TID', null=True)),
                ('title', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Title', max_length=150, null=True)),
                ('kilometer', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Kilometer', max_length=10, null=True)),
                ('spgravity', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='SpGravity', max_length=10, null=True)),
                ('linetitle', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='LineTitle', max_length=150, null=True)),
                ('linecode2', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='LineCode2', max_length=20, null=True)),
            ],
            options={
                'db_table': 'RawOilKarkard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rawoillinedetails',
            fields=[
                ('linedetid', models.AutoField(db_column='LineDetID', primary_key=True, serialize=False)),
                ('linecode', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='LineCode', max_length=20, null=True)),
                ('stationid', models.IntegerField(blank=True, db_column='StationID', null=True)),
            ],
            options={
                'db_table': 'RawOilLineDetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rawoillines',
            fields=[
                ('lineid', models.AutoField(db_column='LineID', primary_key=True, serialize=False)),
                ('linecode', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='LineCode', max_length=20, null=True)),
                ('linename', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='LineName', max_length=100, null=True)),
            ],
            options={
                'db_table': 'RawOilLines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rawoillitr60',
            fields=[
                ('lid', models.AutoField(db_column='LID', primary_key=True, serialize=False)),
                ('stationid', models.IntegerField(blank=True, db_column='StationID', null=True)),
                ('rdate', models.CharField(db_collation='Arabic_BIN', db_column='RDate', max_length=10)),
                ('litr60', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Litr60', max_length=20, null=True)),
                ('unitid', models.SmallIntegerField(blank=True, db_column='UnitID', null=True)),
                ('daryafti', models.BooleanField(blank=True, db_column='Daryafti', null=True)),
            ],
            options={
                'db_table': 'RawOilLitr60',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rawoiltankstock',
            fields=[
                ('rid', models.AutoField(db_column='RID', primary_key=True, serialize=False)),
                ('tankid', models.IntegerField(blank=True, db_column='TankID', null=True)),
                ('rdate', models.CharField(db_collation='Arabic_BIN', db_column='RDate', max_length=10)),
                ('size', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Size', max_length=20, null=True)),
                ('litr1mm', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Litr1mm', max_length=20, null=True)),
                ('cyear', models.IntegerField(blank=True, db_column='CYear', null=True)),
                ('lineid', models.IntegerField(blank=True, db_column='LineID', null=True)),
            ],
            options={
                'db_table': 'RawOilTankStock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rawoiltitles',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Title', max_length=150, null=True)),
                ('isdaryafti', models.BooleanField(blank=True, db_column='ISDaryafti', null=True)),
                ('priority', models.IntegerField(blank=True, db_column='Priority', null=True)),
            ],
            options={
                'db_table': 'RawOilTitles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationid', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='StationID', max_length=10, null=True)),
                ('regionnumb', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Regionnumb', max_length=10, null=True)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regionid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionnumb', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Regionnumb', max_length=10, null=True)),
                ('regionname', models.TextField(blank=True, db_collation='Arabic_BIN', null=True)),
            ],
            options={
                'db_table': 'regionid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reppercentage',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('cyear', models.IntegerField(blank=True, db_column='CYear', null=True)),
                ('tahviliperc', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='TahviliPerc', max_length=10, null=True)),
                ('karkardperc', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='KarkardPerc', max_length=10, null=True)),
            ],
            options={
                'db_table': 'RepPercentage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stationpriority',
            fields=[
                ('spid', models.AutoField(db_column='SPID', primary_key=True, serialize=False)),
                ('stationid', models.IntegerField(blank=True, db_column='StationID', null=True)),
                ('priority', models.IntegerField(blank=True, db_column='Priority', null=True)),
            ],
            options={
                'db_table': 'StationPriority',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tafkiki',
            fields=[
                ('tid', models.AutoField(db_column='TID', primary_key=True, serialize=False)),
                ('linecode', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='LineCode', max_length=20, null=True)),
                ('prodid', models.IntegerField(blank=True, db_column='ProdID', null=True)),
                ('amount', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Amount', max_length=50, null=True)),
                ('date', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Date', max_length=10, null=True)),
                ('stationid', models.IntegerField(blank=True, db_column='StationID', null=True)),
            ],
            options={
                'db_table': 'Tafkiki',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tankcalcmetering',
            fields=[
                ('meterid', models.AutoField(db_column='MeterID', primary_key=True, serialize=False)),
                ('tankid', models.IntegerField(blank=True, db_column='TankID', null=True)),
                ('rdate', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='RDate', max_length=10, null=True)),
                ('temprature', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Temprature', max_length=10, null=True)),
                ('meterno', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='MeterNo', max_length=20, null=True)),
                ('pressure', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Pressure', max_length=20, null=True)),
                ('meterfactor', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='MeterFactor', max_length=20, null=True)),
                ('diff', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Diff', max_length=20, null=True)),
                ('gravity', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Gravity', max_length=20, null=True)),
                ('bsw', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='BSW', max_length=20, null=True)),
                ('ctl', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='CTL', max_length=20, null=True)),
                ('cpl', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='CPL', max_length=20, null=True)),
                ('gsv', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='GSV', max_length=20, null=True)),
                ('nsv', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='NSV', max_length=20, null=True)),
                ('hour', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Hour', max_length=5, null=True)),
                ('cyear', models.IntegerField(blank=True, db_column='CYear', null=True)),
            ],
            options={
                'db_table': 'TankCalcMetering',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tankmotheramount',
            fields=[
                ('amouid', models.AutoField(db_column='AmouID', primary_key=True, serialize=False)),
                ('stationid', models.IntegerField(blank=True, db_column='StationID', null=True)),
                ('prodid', models.IntegerField(blank=True, db_column='ProdID', null=True)),
                ('date', models.DecimalField(blank=True, db_column='Date', decimal_places=0, max_digits=18, null=True)),
                ('litr60', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Litr60', max_length=20, null=True)),
            ],
            options={
                'db_table': 'TankMotherAmount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tankmothergravity',
            fields=[
                ('mgid', models.AutoField(db_column='MGID', primary_key=True, serialize=False)),
                ('tankid', models.IntegerField(blank=True, db_column='TankID', null=True)),
                ('gravity', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Gravity', max_length=20, null=True)),
            ],
            options={
                'db_table': 'TankMotherGravity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tanktype1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanktype', models.CharField(blank=True, db_collation='Arabic_BIN', max_length=10, null=True)),
                ('tanktypeid', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='TankTypeID', max_length=10, null=True)),
            ],
            options={
                'db_table': 'TANKTYPE1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbla1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cm', models.IntegerField(blank=True, db_column='Cm', null=True)),
                ('litr', models.IntegerField(blank=True, db_column='Litr', null=True)),
                ('tank', models.IntegerField(blank=True, db_column='Tank', null=True)),
            ],
            options={
                'db_table': 'Tbla1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblaccount',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('mid', models.IntegerField(blank=True, db_column='Mid', null=True)),
                ('uid', models.IntegerField(blank=True, db_column='Uid', null=True)),
            ],
            options={
                'db_table': 'TblAccount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblentitylinedetail',
            fields=[
                ('eid', models.AutoField(db_column='EId', primary_key=True, serialize=False)),
                ('linecode', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='LineCode', max_length=20, null=True)),
                ('date', models.DecimalField(blank=True, db_column='Date', decimal_places=0, max_digits=18, null=True)),
                ('product', models.IntegerField(blank=True, db_column='Product', null=True)),
                ('size', models.IntegerField(blank=True, db_column='Size', null=True)),
            ],
            options={
                'db_table': 'TblEntityLineDetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblmenu',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('menu', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Menu', max_length=50, null=True)),
            ],
            options={
                'db_table': 'TblMenu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('unitid', models.AutoField(db_column='UnitID', primary_key=True, serialize=False)),
                ('unitname', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='UnitName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Units',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usages',
            fields=[
                ('perfid', models.AutoField(db_column='PerfID', primary_key=True, serialize=False)),
                ('linecode', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='LineCode', max_length=20, null=True)),
                ('stationid', models.IntegerField(blank=True, db_column='StationID', null=True)),
                ('prodid', models.IntegerField(blank=True, db_column='ProdID', null=True)),
                ('date', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Date', max_length=10, null=True)),
                ('litr60', models.TextField(blank=True, db_collation='Arabic_BIN', db_column='Litr60', null=True)),
                ('perfrormance', models.TextField(blank=True, db_collation='Arabic_BIN', db_column='Perfrormance', null=True)),
            ],
            options={
                'db_table': 'Usages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userpower',
            fields=[
                ('userid', models.CharField(db_collation='Arabic_BIN', max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_collation='Arabic_BIN', max_length=50, null=True)),
            ],
            options={
                'db_table': 'userpower',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='FName', max_length=50, null=True)),
                ('lname', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='LName', max_length=50, null=True)),
                ('username', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='UserName', max_length=50, null=True)),
                ('password', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Password', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('calibrid', models.BigAutoField(db_column='CalibrID', primary_key=True, serialize=False)),
                ('tankid', models.IntegerField(blank=True, db_column='TankID', null=True)),
                ('size', models.DecimalField(blank=True, db_column='Size', decimal_places=0, max_digits=18, null=True)),
                ('liters', models.DecimalField(blank=True, db_column='Liters', decimal_places=0, max_digits=18, null=True)),
                ('dasti', models.IntegerField(blank=True, null=True)),
                ('newsize', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('newlitr', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'Calibration',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Calibration2',
            fields=[
                ('calibrid', models.BigAutoField(db_column='CalibrID', primary_key=True, serialize=False)),
                ('tankid', models.IntegerField(blank=True, db_column='TankID', null=True)),
                ('size', models.DecimalField(blank=True, db_column='Size', decimal_places=0, max_digits=18, null=True)),
                ('liters', models.DecimalField(blank=True, db_column='Liters', decimal_places=0, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'Calibration2',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('stationid', models.AutoField(db_column='StationID', primary_key=True, serialize=False)),
                ('stationname', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='StationName', max_length=50, null=True)),
                ('stationno', models.IntegerField(blank=True, db_column='StationNo', null=True)),
                ('isprimary', models.BooleanField(blank=True, db_column='IsPrimary', null=True)),
            ],
            options={
                'db_table': 'Station',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('tankid', models.AutoField(db_column='TankID', primary_key=True, serialize=False)),
                ('tankname', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='TankName', max_length=50, null=True)),
                ('tankno', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='TankNo', max_length=20, null=True)),
                ('stationid', models.IntegerField(blank=True, db_column='StationID', null=True)),
                ('prodid', models.IntegerField(blank=True, db_column='ProdID', null=True)),
                ('ismetric', models.BooleanField(blank=True, db_column='IsMetric', null=True)),
                ('isnew', models.BooleanField(blank=True, db_column='IsNew', null=True)),
                ('tankheight', models.DecimalField(blank=True, db_column='TankHeight', decimal_places=0, max_digits=18, null=True)),
                ('tankhusable', models.DecimalField(blank=True, db_column='TankHUsable', decimal_places=0, max_digits=18, null=True)),
                ('tankhunusable', models.DecimalField(blank=True, db_column='TankHUnUsable', decimal_places=0, max_digits=18, null=True)),
                ('volinheight', models.DecimalField(blank=True, db_column='VolInHeight', decimal_places=0, max_digits=18, null=True)),
                ('rdate', models.DateTimeField(blank=True, db_column='Rdate', null=True)),
                ('materialh', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='MaterialH', max_length=50, null=True)),
                ('materiall', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='MaterialL', max_length=50, null=True)),
                ('heademptyh', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='HeadEmptyH', max_length=50, null=True)),
                ('heademptyl', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='HeadEmptyL', max_length=50, null=True)),
                ('recoverableh', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='RecoverableH', max_length=50, null=True)),
                ('recoverablel', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='RecoverableL', max_length=50, null=True)),
                ('increasemili', models.DecimalField(blank=True, db_column='IncreaseMili', decimal_places=0, max_digits=18, null=True)),
                ('tanktype', models.SmallIntegerField(blank=True, db_column='TankType', null=True)),
                ('tankcaptot', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='TankCapTot', max_length=50, null=True)),
                ('tankcapallowed', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='TankCapAllowed', max_length=50, null=True)),
                ('enabled', models.BooleanField(blank=True, db_column='Enabled', null=True)),
            ],
            options={
                'db_table': 'Tank',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tankcalcmetric',
            fields=[
                ('calcid', models.AutoField(db_column='CalcID', primary_key=True, serialize=False)),
                ('tankid', models.IntegerField(db_column='TankID')),
                ('rdate', models.CharField(db_collation='Arabic_BIN', db_column='RDate', max_length=10)),
                ('billid', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='BillID', max_length=10, null=True)),
                ('size', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Size', max_length=20, null=True)),
                ('temprature', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Temprature', max_length=20, null=True)),
                ('water', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Water', max_length=20, null=True)),
                ('status', models.SmallIntegerField(blank=True, db_column='Status', null=True)),
                ('specweight', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='SpecWeight', max_length=20, null=True)),
                ('refinery', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Refinery', max_length=50, null=True)),
                ('naturallitr', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='NaturalLitr', max_length=20, null=True)),
                ('litr60', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Litr60', max_length=20, null=True)),
                ('hour', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='Hour', max_length=5, null=True)),
                ('cyear', models.IntegerField(blank=True, db_column='CYear', null=True)),
                ('envtemp', models.CharField(blank=True, db_collation='Arabic_BIN', db_column='EnvTemp', max_length=20, null=True)),
            ],
            options={
                'db_table': 'TankCalcMetric',
                'managed': True,
            },
        ),
    ]
