# Generated by Django 3.2.16 on 2023-02-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TankCalcMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TankID', models.IntegerField()),
                ('RDate', models.CharField(max_length=10)),
                ('BillID', models.CharField(max_length=10)),
                ('Size', models.CharField(max_length=20)),
                ('Temprature', models.CharField(max_length=20)),
                ('Water', models.CharField(max_length=20)),
                ('Status', models.IntegerField()),
                ('SpecWeight', models.CharField(max_length=20)),
                ('Refinery', models.CharField(max_length=50)),
                ('NaturalLitr', models.CharField(max_length=50)),
                ('Litr60', models.CharField(max_length=20)),
                ('Hour', models.CharField(max_length=20)),
                ('CYear', models.IntegerField()),
                ('EnvTemp', models.CharField(max_length=20)),
            ],
        ),
    ]
