# Generated by Django 3.2.17 on 2023-03-04 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_regidentification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station_Region_Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regname', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.regidentification')),
                ('stationname', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.station')),
            ],
        ),
    ]
