# Generated by Django 3.2.17 on 2023-04-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20230426_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tanktype1',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='tank_calibration_excel',
            name='Calibration_in_milimeter',
            field=models.BooleanField(default=False),
        ),
    ]
