# Generated by Django 3.2.17 on 2023-04-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20230427_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank_calibration_excel',
            name='max_height',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='tank_calibration_excel',
            name='max_operation_height',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='tank_calibration_excel',
            name='min_operation_height',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
