# Generated by Django 3.2.17 on 2023-05-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20230430_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank_calibration_excel',
            name='type',
            field=models.IntegerField(choices=[(0, 'خط لوله '), (2, 'پخش '), (3, 'الوده'), (4, 'پالایشگاه'), (5, 'بندر صادرات'), (6, 'پتروشیمی'), (7, 'نیروگاه')], default=0, max_length=2),
        ),
    ]
