# Generated by Django 3.2.17 on 2023-05-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_tank_calibration_excel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank_calibration_excel',
            name='type',
            field=models.IntegerField(choices=[(0, 'خط لوله '), (2, 'پخش '), (3, 'الوده'), (4, 'پالایشگاه'), (5, 'بندر صادرات'), (6, 'پتروشیمی'), (7, 'نیروگاه')], default=0),
        ),
    ]
