# Generated by Django 3.2.17 on 2023-04-17 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0004_reg'),
        ('accounts', '0002_person_person_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='more_information',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='person',
            name='person_station',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.station'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
