# Generated by Django 3.2.17 on 2023-04-16 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ioptc_region',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='region_name',
            new_name='person_name',
        ),
    ]
